# DOCKERFILE FOR NODE.JS APPLICATION

# INSTALL NODE AS BASE IMAGE B/C ITS NODE APP
FROM node:lts-alpine3.18

# IT WILL COPY PACKAGE.JSON FILE TO MYAPP DIR.
COPY package.json /myapp/

#IT WILL SOURCE CODE FILE THAT IS SERVER.JS TO MYAPP DIR. 
COPY src /myapp/

#IT WILL SET WORKDIR AS MYAPP TO RUN NPM INSTALL CMD
WORKDIR /myapp

#IT WILL LOOK FOR DEPENDENCIES IN PACKAGE.JSON FILE (THAT IS NEEDED TO RUN NODE APP) AND INSTALL IT 
RUN npm install

#IT WILL START NODE APP 
CMD ["node", "server.js"]

